# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConfirmDemon' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ConfirmDemon

  target 'ConfirmDemonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConfirmDemonUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Masonry'
pod 'MJExtension'
end
